apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-test12345
  # namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: apache:1.2
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:////opt/spark/work-dir/test.py
  sparkVersion: "3.4.0"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.0
